[workspace]

members = [
    "extend_map",
    "deterministic_default_hasher",
    "generic_a_star",
    "seed_chain",
    "lib_tsalign",
    "tsalign",
]
resolver = "2"
package.rust-version = "1.83.0"
package.repository = "https://github.com/sebschmi/template-switch-aligner"

[workspace.dependencies]
serde = "1.0.216"
compact-genome = "12.0.0"
traitsequence = "3.0.0"
log = "0.4.22"
num-traits = "0.2.19"
