[package]
name = "tsalign"
description = "A sequence-to-sequence aligner that accounts for template switches"
license = "BSD-2-Clause"
repository = "https://github.com/sebschmi/template-switch-aligner"
authors = ["Sebastian Schmidt <sebastian.schmidt@helsinki.fi>"]
version = "0.3.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
lib_tsalign = { version = "0.3.0", path = "../lib_tsalign" }
clap = { version = "4.5.16", features = ["derive"] }
compact-genome = { workspace = true, features = ["io"] }
traitsequence.workspace = true
