[package]
name = "lib_tsalign"
description = "A sequence-to-sequence aligner that accounts for template switches"
license = "BSD-2-Clause"
repository = "https://github.com/sebschmi/template-switch-aligner"
authors = ["Sebastian Schmidt <sebastian.schmidt@helsinki.fi>"]
version = "0.2.0"
edition = "2021"
rust-version = "1.80.1"

[dependencies]
compact-genome.workspace = true
traitsequence.workspace = true
ndarray = "0.16.1"
