[package]
name = "lib_tsshow"
description = "A visualiser for template-switch alignments"
license.workspace = true
authors = ["Sebastian Schmidt <sebastian.schmidt@helsinki.fi>"]
version = "6.0.1"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
lib_tsalign = { version = "6.0.1", path = "../lib_tsalign" }
log.workspace = true
svg = "0.18.0"
base64 = "0.22.1"
fontcull = { version = "2.0.1", default-features = false }
ttf-parser = "0.25.1"
resvg = "0.48.1"
thiserror.workspace = true
tagged-vec = "1.1.0"
strong-type = "1.1.1"
ena = "0.14.3"
itertools.workspace = true
clap.workspace = true
