type = "WithTarget"
alignment = [[1, "PrimarySubstitution"], [1, "PrimaryMatch"], [152, { TemplateSwitchEntrance = { first_offset = -151, equal_cost_range = { min_start = 0, max_start = 0, min_end = 0, max_end = 0 }, primary = "Reference", secondary = "Reference", direction = "Reverse" } }], [7, "SecondaryMatch"], [1, "SecondarySubstitution"], [2, "SecondaryMatch"], [69, { TemplateSwitchExit = { anti_primary_gap = 78 } }], [273, { TemplateSwitchEntrance = { first_offset = 272, equal_cost_range = { min_start = 0, max_start = 0, min_end = 0, max_end = 0 }, primary = "Query", secondary = "Reference", direction = "Reverse" } }], [5, "SecondaryMatch"], [1, "SecondaryInsertion"], [4, "SecondaryMatch"], [85, { TemplateSwitchExit = { anti_primary_gap = 94 } }], [2, "PrimaryMatch"], [1, "PrimarySubstitution"], [1, "PrimaryMatch"]]
reference_offset = 200
query_offset = 164
cost = 24.0
cost_per_base = 0.05263157894736842
duration_seconds = 69.622919049
opened_nodes = 50127278.0
closed_nodes = 22733640.0
suboptimal_opened_nodes = 4326095.0
suboptimal_opened_nodes_ratio = 0.09445378299508116
template_switch_amount = 2.0
runtime = 0.0
memory = 0.0

[result]
astar_result_type = "FoundTarget"
cost = 24

[sequences]
reference_name = "Homo_sapiens "
reference = "TCTTTACGGTGAACATCAGAGAAAACCCCCTCCTGTTGCAGTAACAGTTTTGAAATACACCAAGGGTGTTCCGGTCTCCCTAACAAAAACTTGCCTTCTCAGGGAAAATGCTTTGACAAAGTCTTCTCTGACCTAGGGGAAAAGCAGACACTCAACTCTGGCTGTATCTATCTGTCCTGTCTCCTTTGAAAGAGAAAGAAAAAAAACTGCTATGAAACAATTCTGGTCACAGGCCAGAAATTCAGCCTTATTTTAAAAATAGGACCTTACCAACATTCATCAACAGGGCTTCCATATAGTAAGAGTGGATTACAACTGAGAGAGCAGTAAGCCACAGACTCTATTTAGGAAATAGTTCTCAAGGAATCCCAGACAAGAGAGTGAAGAAACAACATCACAAGTCAACTACGGAAAACTAAAACCTGTGGCACTTACAGCTATAGCAAATACTAAACAAAACCCAGCTCATAGTCAGATTAACATAAAACCTCAC"
reference_rc = "GTGAGGTTTTATGTTAATCTGACTATGAGCTGGGTTTTGTTTAGTATTTGCTATAGCTGTAAGTGCCACAGGTTTTAGTTTTCCGTAGTTGACTTGTGATGTTGTTTCTTCACTCTCTTGTCTGGGATTCCTTGAGAACTATTTCCTAAATAGAGTCTGTGGCTTACTGCTCTCTCAGTTGTAATCCACTCTTACTATATGGAAGCCCTGTTGATGAATGTTGGTAAGGTCCTATTTTTAAAATAAGGCTGAATTTCTGGCCTGTGACCAGAATTGTTTCATAGCAGTTTTTTTTCTTTCTCTTTCAAAGGAGACAGGACAGATAGATACAGCCAGAGTTGAGTGTCTGCTTTTCCCCTAGGTCAGAGAAGACTTTGTCAAAGCATTTTCCCTGAGAAGGCAAGTTTTTGTTAGGGAGACCGGAACACCCTTGGTGTATTTCAAAACTGTTACTGCAACAGGAGGGGGTTTTCTCTGATGTTCACCGTAAAGA"
query_name = "PrimatesAnc069 "
query = "CTCTCCTGCTTAAGAACAGCTGCAGCCCACTCTGCCCCAGCATCCCCTTCTGCTGGAAGCTGGCTCTTTCTTACATCTGCAACTACTGAGGCTGTTAGGGAGGTGCCCTCCTCTGCATCTGTTTCACAGTCCCCATGCAGAGGCCAGGCTTCCTCTAGAGATACCACAAGCAGCTTTGCTGGTCCCCCAACTGCTTTCACATCTGTTTGATTTGTCCCCTCCACAGACACCTGATGCTTCTTTATATGTATAATGGCTGACCCTGGCGGGACTTCCTTCTCCACTTGTGTGTTGATGTCCACTGTGGTGGAGGCTTGGCTTCTCTCCAGGTGGATCCCAGGTGAGCTCTTATCTGCTTCCACACTGTCATCACTGTCCCCAAAAGGAGGTTGGTCCTTTTCTGAATGTGCTCTAACAAG"
query_rc = "CTTGTTAGAGCACATTCAGAAAAGGACCAACCTCCTTTTGGGGACAGTGATGACAGTGTGGAAGCAGATAAGAGCTCACCTGGGATCCACCTGGAGAGAAGCCAAGCCTCCACCACAGTGGACATCAACACACAAGTGGAGAAGGAAGTCCCGCCAGGGTCAGCCATTATACATATAAAGAAGCATCAGGTGTCTGTGGAGGGGACAAATCAAACAGATGTGAAAGCAGTTGGGGGACCAGCAAAGCTGCTTGTGGTATCTCTAGAGGAAGCCTGGCCTCTGCATGGGGACTGTGAAACAGATGCAGAGGAGGGCACCTCCCTAACAGCCTCAGTAGTTGCAGATGTAAGAAAGAGCCAGCTTCCAGCAGAAGGGGATGCTGGGGCAGAGTGGGCTGCAGCTGTTCTTAAGCAGGAGAG"
