type = "WithTarget"
alignment = [[259, { TemplateSwitchEntrance = { first_offset = 258, equal_cost_range = { min_start = 0, max_start = 0, min_end = 0, max_end = 0 }, primary = "Query", secondary = "Reference", direction = "Reverse" } }], [2, "SecondaryInsertion"], [1, "SecondaryMatch"], [2, "SecondaryInsertion"], [5, "SecondaryMatch"], [80, { TemplateSwitchExit = { anti_primary_gap = 89 } }], [191, { TemplateSwitchEntrance = { first_offset = 190, equal_cost_range = { min_start = 0, max_start = 0, min_end = 0, max_end = 0 }, primary = "Reference", secondary = "Query", direction = "Reverse" } }], [8, "SecondaryMatch"], [1, "SecondaryInsertion"], [1, "SecondaryMatch"], [83, { TemplateSwitchExit = { anti_primary_gap = 92 } }], [1, "PrimaryMatch"]]
reference_offset = 176
query_offset = 199
cost = 25.0
cost_per_base = 0.05411255411255411
duration_seconds = 73.751287724
opened_nodes = 57674257.0
closed_nodes = 26087037.0
suboptimal_opened_nodes = 5108914.0
suboptimal_opened_nodes_ratio = 0.0971916800771185
template_switch_amount = 2.0
runtime = 0.0
memory = 0.0

[result]
astar_result_type = "FoundTarget"
cost = 25

[sequences]
reference_name = "Homo_sapiens "
reference = "TCCATGTCCCACTGAACTACAAGTACATGGAGCAAATTTAAAGATAAAAATATTAAGAGTCTTGAGACAGAAATAGGAGAGCATTAAACCAAGTACGGGCCTTTCTAAGTCCAGGTCCCATCATACAAGTTGCCTGCTCATGAAGCTGGCCCTATGATGGTTAGTTTCATAATTCCGGAATTCAGGACAGAGGTCCAAGCTACACATCTTTATTTACAACTTTATTTCACCAGACTCAAACTGAAATTTAATGTTTCCTTTGATTATGTATATAGGCAACAAACTACAATAGTATTAGTACTACCTATAAGCTTGTCACCAGTAAAAATCACATATGTGATTTTCACATCACAAAATACAATTATTGTAGATATATTAAAATAGAATTGATGTTTATCATTACCTTAACATTATGATAATTGGCTGGGGGCAGT"
reference_rc = "ACTGCCCCCAGCCAATTATCATAATGTTAAGGTAATGATAAACATCAATTCTATTTTAATATATCTACAATAATTGTATTTTGTGATGTGAAAATCACATATGTGATTTTTACTGGTGACAAGCTTATAGGTAGTACTAATACTATTGTAGTTTGTTGCCTATATACATAATCAAAGGAAACATTAAATTTCAGTTTGAGTCTGGTGAAATAAAGTTGTAAATAAAGATGTGTAGCTTGGACCTCTGTCCTGAATTCCGGAATTATGAAACTAACCATCATAGGGCCAGCTTCATGAGCAGGCAACTTGTATGATGGGACCTGGACTTAGAAAGGCCCGTACTTGGTTTAATGCTCTCCTATTTCTGTCTCAAGACTCTTAATATTTTTATCTTTAAATTTGCTCCATGTACTTGTAGTTCAGTGGGACATGGA"
query_name = "PrimatesAnc069 "
query = "CGGCTGCTCCCACACTCTGTGTCCAAGACTCTCGGACGTGAGGCTGAGAGCGGGAGTGGCAGAGCCTTCTTTAGCTTCACCTGCAGCTGCCGGCCACGTGCTCTGACACCTCTGAGGCCTACATCTCCAGATCGCACCTTCCATGGGTCCTTGCTTTGTATTTTCCCGCAACTGGACTCATGCCTCCTTTCTCATTCTGCAAACCTGCCAAGGCCATGCAGGCACTCTGGCTCTCAAAACCAGCTGGGATGCCAGGACTGAGGCTCACTCTGAACCACCTGCGTGCCCAGGGCTGGGCAAAGACCTGGTGCAGCCAAACCTCAGAGGAGGAAAGGCAACGTTGTGAGCAAATTAGAAAGGGGTCGGGGGAGAAATTCATACACACATACACATATACATGCATACACACATGTATACACACACATGCACACGCACACACACATACATATATACACACATACATGCATACACACATACACACATACACATA"
query_rc = "TATGTGTATGTGTGTATGTGTGTATGCATGTATGTGTGTATATATGTATGTGTGTGTGCGTGTGCATGTGTGTGTATACATGTGTGTATGCATGTATATGTGTATGTGTGTATGAATTTCTCCCCCGACCCCTTTCTAATTTGCTCACAACGTTGCCTTTCCTCCTCTGAGGTTTGGCTGCACCAGGTCTTTGCCCAGCCCTGGGCACGCAGGTGGTTCAGAGTGAGCCTCAGTCCTGGCATCCCAGCTGGTTTTGAGAGCCAGAGTGCCTGCATGGCCTTGGCAGGTTTGCAGAATGAGAAAGGAGGCATGAGTCCAGTTGCGGGAAAATACAAAGCAAGGACCCATGGAAGGTGCGATCTGGAGATGTAGGCCTCAGAGGTGTCAGAGCACGTGGCCGGCAGCTGCAGGTGAAGCTAAAGAAGGCTCTGCCACTCCCGCTCTCAGCCTCACGTCCGAGAGTCTTGGACACAGAGTGTGGGAGCAGCCG"
