type = "WithTarget"
alignment = [[1, "PrimaryMatch"], [165, { TemplateSwitchEntrance = { first_offset = 164, equal_cost_range = { min_start = 0, max_start = 0, min_end = 0, max_end = 0 }, primary = "Reference", secondary = "Query", direction = "Reverse" } }], [6, "SecondaryMatch"], [2, "SecondaryInsertion"], [2, "SecondaryMatch"], [92, { TemplateSwitchExit = { anti_primary_gap = 101 } }], [151, { TemplateSwitchEntrance = { first_offset = -150, equal_cost_range = { min_start = 0, max_start = 0, min_end = -1, max_end = 0 }, primary = "Query", secondary = "Reference", direction = "Reverse" } }], [8, "SecondaryMatch"], [1, "SecondarySubstitution"], [3, "SecondaryMatch"], [101, { TemplateSwitchExit = { anti_primary_gap = 112 } }], [1, "PrimarySubstitution"], [1, "PrimaryMatch"]]
reference_offset = 158
query_offset = 188
cost = 23.0
cost_per_base = 0.04791666666666667
duration_seconds = 97.240702419
opened_nodes = 83345497.0
closed_nodes = 37710749.0
suboptimal_opened_nodes = 6880197.0
suboptimal_opened_nodes_ratio = 0.08997802924986889
template_switch_amount = 2.0
runtime = 0.0
memory = 0.0

[result]
astar_result_type = "FoundTarget"
cost = 23

[sequences]
reference_name = "Homo_sapiens "
reference = "CCTTGGCTCATGCGTGAGGTTGCCTGGTTGCCGCAGTGCCTGCTTTTCTCCCTGTGTCACTTTAGTTGTCTCCTGAATAACAGTTTCAGGTTTGTCTATGGCTTCTTCGGGGAGCTGAGACACCTGGACAGAGTGGGCCACACAAATCAAGTGGGACACATCTCCCCTGTCAGCTGGAGTCTCACTCCGTGCAGGCATGGAAATCCCCATATGGGCCACCAGGTTGTGAGAAACAGACTCACCCGTCCAAACCCAAAGAATGGACTCAGAGACCCAGAGAACAGCGAAAGTGAGACTTGTGATGACGGTCTTGCAAAATCGGGTGTCTGATGAGCAGGCACACCCAGCACAGTTTCAACAAGCAGTTTATCCCCTAGTGCACAGGTCTCTCCCCTGGTTCCTCATAGGCTGAGTATTATGGGTTACAATCTTCCCGGATGATGCCTGTTCATTGCTGGG"
reference_rc = "CCCAGCAATGAACAGGCATCATCCGGGAAGATTGTAACCCATAATACTCAGCCTATGAGGAACCAGGGGAGAGACCTGTGCACTAGGGGATAAACTGCTTGTTGAAACTGTGCTGGGTGTGCCTGCTCATCAGACACCCGATTTTGCAAGACCGTCATCACAAGTCTCACTTTCGCTGTTCTCTGGGTCTCTGAGTCCATTCTTTGGGTTTGGACGGGTGAGTCTGTTTCTCACAACCTGGTGGCCCATATGGGGATTTCCATGCCTGCACGGAGTGAGACTCCAGCTGACAGGGGAGATGTGTCCCACTTGATTTGTGTGGCCCACTCTGTCCAGGTGTCTCAGCTCCCCGAAGAAGCCATAGACAAACCTGAAACTGTTATTCAGGAGACAACTAAAGTGACACAGGGAGAAAAGCAGGCACTGCGGCAACCAGGCAACCTCACGCATGAGCCAAGG"
query_name = "PrimatesAnc069 "
query = "CATCCACTAGATCTATTTGTAATCATGTTATTTAAATCCTATTTACCTTTTCTGAGTTTTGTCTTTTTATTCTATTATTTCTTGAGATTTAATGTTAAACTATCCTGCTATGAGTATAGGTTTATCTATGTCTTTTAGAAGTCCTGTCAACTTTTACTTTACATATTTTGATGCCATGCTGATGAGTGCATAGAGCGTTAGAATTGTAGTATCTTCATGGCAAATATAACCTCTACTCACATGAGGTGACATTATCTATTCTAATGTCTTTTTCCTTAAAATCTATTTAGCCTCACGCCTGAAATCCCAGCACTTTGGGAGGCCGAGGCGGGTGGATCATGAGGTCAGGAGATCGAGACCAGCATGGCTAACACATGGTGAAACCAAGTCTCTACTAAAACTACAAAAAATTAGCCGGGCATGGTGGCAGGCACCTGTAGTCCCAGCTACTCGGGAGGCAGAGGCAAGAGAATGGCAGGAACCTGGGAGGTGGAGCTTGCA"
query_rc = "TGCAAGCTCCACCTCCCAGGTTCCTGCCATTCTCTTGCCTCTGCCTCCCGAGTAGCTGGGACTACAGGTGCCTGCCACCATGCCCGGCTAATTTTTTGTAGTTTTAGTAGAGACTTGGTTTCACCATGTGTTAGCCATGCTGGTCTCGATCTCCTGACCTCATGATCCACCCGCCTCGGCCTCCCAAAGTGCTGGGATTTCAGGCGTGAGGCTAAATAGATTTTAAGGAAAAAGACATTAGAATAGATAATGTCACCTCATGTGAGTAGAGGTTATATTTGCCATGAAGATACTACAATTCTAACGCTCTATGCACTCATCAGCATGGCATCAAAATATGTAAAGTAAAAGTTGACAGGACTTCTAAAAGACATAGATAAACCTATACTCATAGCAGGATAGTTTAACATTAAATCTCAAGAAATAATAGAATAAAAAGACAAAACTCAGAAAAGGTAAATAGGATTTAAATAACATGATTACAAATAGATCTAGTGGATG"
