[package]
name = "deterministic_default_hasher"
description = "A deterministic initialisation of the stdlib default hasher"
version = "0.7.1"
edition.workspace = true
rust-version.workspace = true
license = "BSD-2-Clause"
repository.workspace = true

[dependencies]
