[package]
name = "deterministic_default_hasher"
description = "A deterministic initialisation of the stdlib default hasher"
version = "0.6.0"
edition = "2021"
rust-version.workspace = true
license = "BSD-2-Clause"

[dependencies]
