[package]
name = "extend_map"
description = "A type to map values passed into an Extend type before extending."
version = "0.14.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
